### ISSUE TITLE
Azure template step "Set Variables for Notification" - issue with assigning insights_url variable

### ISSUE THREAD

**Issue by kf-maciejgrzesiak** [ObjectivityLtd/jmeter_azure_maven_boilerplate#2] opened 2020-06-25 11:29 UTC
Concatenating values( from *.properties files) for insights_url variable where files don't contain an empty line at the EOF causes that extracted variables are displayed in one line without any delimiter which results that 'Insights' button is not displayed on ChatOps channel on Teams. 

![image](https://user-images.githubusercontent.com/29894496/85711786-eaba4d00-b6e7-11ea-8d63-c7339fab26eb.png)

**Comment by gabrielstar** [comment] 2020-06-29 13:16
@kf-maciejgrzesiak - I am not able to reproduce. Can you give me specific steps please? I have removed EOL and this still works fine for me on Windows Git Bash. Perhaps there is somethign missing here.

I have committed new test so you cna check yourself

`@test "When base.user.properties has no new line at EOF insights_url is correctly extracted "`

1. Go to modules/bats directory
2.  Execute `sh install.sh`
3. Run all test with `sh run_all_tests.sh`

**Comment by gabrielstar** [comment] 2020-06-30 09:42
fixed

**Closed** 2020-06-30 09:42 UTC
